### ISSUE TITLE
Send Open Connections DIgest Plugin Does Not Show Error When It Should

### ISSUE THREAD

**Issue by mikedotmundy** [BEMADEV/Open-Connections-Digest#3]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

I just happened to notice today that our Send Open Connections Digest Plugin is not sending emails. I am not sure what happened, or why, but the reason is because there was no System Communication selected in the Job Settings.

![Screenshot 2024-07-24 at 09 21 54](https://github.com/user-attachments/assets/3cadf920-722a-4eed-a0b4-1b1145bdc6ae)

So, it is completely my error.

However, the job has been running "succuessfully" for some time. Every Wednesday, it will run and show that reminders were sent successfully: 
![Screenshot 2024-07-24 at 09 23 01](https://github.com/user-attachments/assets/00c30412-4f15-436a-858f-00755db6beaf)

I feel like it should have had an error since reminders were not actually being sent out. 

### Expected Behavior

Job should have shown an error since reminders were not sent.

### Actual Behavior

Job showed that it was sending reminders successfully when it was not.

### Steps to Reproduce

Steps to reproduce are tough because technically, you cannot save the job without adding a System Communication since that field is required.

I do not know how that field got emptied out.

### Rock Version

v16.5

### Plugin Version

2.0.1.13

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/VQ4xSiOq/536-test)
